- include: CentOS.yml
  when: "ansible_os_family == 'RedHat'"
  tags: docker

- include: Ubuntu.yml
  when: "ansible_os_family == 'Debian'"
  tags: docker

- name: put /etc/docker/daemon.json
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  tags: docker
