- include: CentOS.yml
  when: "ansible_os_family == 'RedHat'"

- include: Ubuntu.yml
  when: "ansible_os_family == 'Debian'"
- name: put /etc/docker/daemon.json
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
    backup: true
