---
- name: apt install docker require packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      
- name: software-properties-common install
  package:
    name: software-properties-common
    state: present
- name: set dockers official gpg key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  register: set_key

- block:
    - name: amd64 set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
  when:
    - ansible_architecture != "aarch64"
    - ansible_architecture != "armv7l"

- block:
    - name: arm64 set up the stable repository
      apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        update_cache: no
  when:
    - ansible_architecture == "aarch64" or ansible_architecture == "armv7l"

- name: apt install pip3
  apt:
    name: python3-pip
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: install docker-ce
  apt:
    pkg: docker-ce
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install docker-compose package
  pip:
    name: docker-compose

- name: docker.service set
  template:
    src: "ubuntu_docker.service"
    dest: /etc/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644
    backup: true

# systemdにconfigsを読み直すように強制する
# servicedの再読込（/etc/systemd/system/のファイルを変更した場合に必須）
- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes
  ignore_errors: true

# docker ipv4 forward-----------------------------------------------------------------------------------------
- name: add kernel parameters and reload
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
