---
- name: apt-transport-https install
  package:
    name: apt-transport-https
    state: present

- name: ca-certificates install
  package:
    name: ca-certificates
    state: present

- name: curl install
  package:
    name: curl
    state: present

- name: software-properties-common install
  package:
    name: software-properties-common
    state: present

- name: set dockers official gpg key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  register: set_key

- name: set up the stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: install docker-ce
  apt:
    pkg: docker-ce
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "docker-compose Download"
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    dest: /usr/bin/docker-compose
    owner: root
    group: root
    mode: 0755

- name: "docker-compose permission set"
  file:
    path: /usr/bin/docker-compose
    owner: root
    group: root
    mode: 0755

- name: docker.service set
  template:
    src: "ubuntu_docker.service"
    dest: /etc/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644

# systemdにconfigsを読み直すように強制する
# servicedの再読込（/etc/systemd/system/のファイルを変更した場合に必須）
- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes
  ignore_errors: true

# docker ipv4 forward-----------------------------------------------------------------------------------------
- name: add kernel parameters and reload
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
    ignoreerrors: yes
